name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_NAME_BACKEND: salah0250/potioncraft-backend
      IMAGE_NAME_FRONTEND: salah0250/potioncraft-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: |
            ${{ env.IMAGE_NAME_BACKEND }}:latest
            ${{ env.IMAGE_NAME_BACKEND }}:v1
            ${{ env.IMAGE_NAME_BACKEND }}:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.IMAGE_NAME_FRONTEND }}:latest
            ${{ env.IMAGE_NAME_FRONTEND }}:v1
            ${{ env.IMAGE_NAME_FRONTEND }}:${{ github.sha }}